server:
  port: ${PORT}
  servlet:
    context-path: /api

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: ${DB_POOL_MAX_SIZE:5}
      minimum-idle: ${DB_POOL_MIN_IDLE:1}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:20000}

  data:
    redis:
      url: ${REDIS_URL}

  jpa:
    show-sql: false

logging:
  level:
    root: ${ROOT_LOG_LEVEL:WARN}
    ec.edu.ups.icc.proyecto: ${APP_LOG_LEVEL:INFO}

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}
  issuer: ${JWT_ISSUER:proyecto-api}
  header: Authorization
  prefix: "Bearer "

cors:
  allowed-origins: ${ALLOWED_ORIGINS}